name: flutter_dialogflow
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter: ^0.3.3
  cupertino_icons: ^1.0.2
  table_calendar: ^3.2.0
  http: 0.13.6
  intl: ^0.20.0
  url_launcher: ^6.2.4
  provider: ^6.0.5
  image_picker: ^0.8.7+1
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.12.0
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^6.0.0
  webview_flutter_android: ^4.3.2  
  webview_flutter_wkwebview: ^3.2.1  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dialog_flow_auth.json
    # - assets/water.png
    # - assets/vaccine.png
    # - assets/exercise.png
    # - assets/meditation.png
